---
title: "Cancer Classification With RNA-Seq Data"
author: "B. D. Schedin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
      toc: true
---

```{r setup, include=FALSE}

# Global chunk options
knitr::opts_chunk$set(echo = TRUE)

# Project paths
projRoot <- "C:/_git_/cancer-classification-rna-seq-data/"

# Project libraries
library(tidyverse)
library(e1071)

```

# 1. Abstract





# 2. Introduction





# 3. Methods and Results





# 4. Conclusion





# 5. Appendix

## Dataset Information

## Preprocessing
```{r, eval=FALSE}

# Loading raw data
rawData <- read.csv(paste0(projRoot, "data/raw/data.csv"))
rawLabels <- read.csv(paste0(projRoot, "data/raw/labels.csv"))

# Setting sample IDs to row names, removing sample ID columns
data <- rawData
rownames(data) <- rawData$X
data <- data %>% select(-X)

labels <- rawLabels
rownames(labels) <- rawLabels$X
labels <- labels %>% select(-X)

# Checking for missing values
missing <- sapply(data, function(x) sum(is.na(x)))
cat("Found", length(missing[missing > 0]), "columns with missing values.\n")

# Removing genes which are not expressed for more than 25% of samples
preCounts <- map_int(data, function(x) sum(x == 0))
data <- data[colMeans(data == 0) <= 0.25]
postCounts <- map_int(data, function(x) sum(x == 0))

cat("Removed", length(preCounts) - length(postCounts), "columns containing genes unexpressed in more than 25% of samples.\n")

# Scaling features
data <- scale(data)

# Exporting preprocessed data to file
save("data", "labels", file=paste0(projRoot, "data/processed/rna-seq-preprocessed"))

```

## Principal Component Analysis and Random Sampling
```{r}

# Setting seed for reproducibility
set.seed(123)

# Loading preprocessed data
load(paste0(projRoot, "data/processed/rna-seq-preprocessed"))
data <- as.data.frame(data)

# Random sample of 1000 genes
sampleIndices <- sample(1:dim(data)[[2]], 1000, replace=FALSE)
sample1000 <- data[, sampleIndices]

# PCA on all features
pca <- prcomp(data)
plot(pca, main="Scree Plot", xlab="PCs")

cumVar <- cumsum((nrow(data) - 1) * ((pca$sdev)^2)/sum(data^2))
cumVarData <- data.frame(PC = 1:length(cumVar), CumulativeVariance = cumVar)

ggplot(cumVarData, aes(x=PC, y=CumulativeVariance)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  labs(title="Component Cumulative Variance", x="PC", y="Variance")
ggsave(paste0(projRoot, "figures/pca-cumulative-variance.png"), device="png", width=5, height=4)

# Number of features to reach 50% cumulative variance
cat("Number of components required to reach 50% cumulative variance:", length(cumVar[cumVar <= 0.50]), "\n")

```

## K-Means Clustering 
```{r}

```

## Hierarchical Clustering
```{r}

```

## K-Nearest Neighbors
```{r}

```

## Support Vector Machines
```{r}

```

## Linear Discriminant Analysis
```{r}

```

## Quadratic Discriminant Analysis
```{r}

```

## Neural Network
```{r}

```













